name: Tag

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # get existing tags
      - name: List existing tags
        run: |
          git tag -l
      - name: Create tag from VERSION.yaml
        id: create_tag
        uses: mikefarah/yq@v4
        with:
          cmd: yq -r '"v" + (.MAJ | tostring) + "." + (.MIN | tostring)' ecoscope-workflows-patrols-workflow/VERSION.yaml
      - name: Tag
        # `mikefarah/yq@v4` assigns result of `cmd` to `${{ steps.create_tag.outputs.result }}`,
        # so we can use that here; see https://mikefarah.gitbook.io/yq/usage/github-action#guide
        run: |
          echo "Tagging version ${{ steps.create_tag.outputs.result }}"
          git tag ${{ steps.create_tag.outputs.result }}
          git tag -l
      - name: Push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git push origin --tags
      - name: Create GitHub Release
        run: >-
          gh release create
          '${{ steps.create_tag.outputs.result }}'
          --repo '${{ github.repository }}'
          --generate-notes
